### ISSUE TITLE
PEP8 Compliance

### ISSUE THREAD

**Issue by jnmclarty** [Equitable/trump#12]
Moving towards PEP 8 compliance:

Goal is to clean up orm.py and templates.py first, then do the rest.
## Greater than 6 / 10
- [X] orm.py
- [x] templates.py
- [x] all other non-doc files
## Greater than 8 / 10
- [X] orm.py
- [x] templates.py
- [x] all other non-doc files

**Comment by jnmclarty** [comment]
I create a branch named "PEP8".  Going to merge into master tomorrow or Sunday.

The entire project has had autopep8 ran, and I manually cleaned up orm.py...started at a negative score, it's now >8.

**Comment by jnmclarty** [comment]
There are three pylint errors in orm.py that are false negatives. Ones a decorated SQLAlchemy function, the other two are callable properties. (ie, properties that return a callable object).

We're going to keep using _args and *_kwargs, wether pylint likes it or not.

The camel case methods will get cleaned up as tests are written for each.

The TODO items should move to github issues.

**Comment by jnmclarty** [comment]
templating.templates.py is above 6 now.

**Comment by jnmclarty** [comment]
templating and orm are both above 9 / 10, with certain rules silences explicitly.

**Comment by kissgyorgy** [comment]
I commented all over the place. Don't take them as offending, I'm here to help.

**Comment by jnmclarty** [comment]
I really appreciate the help.  Everything you're saying is right, and should/will be (80%) implemented within the weekend.  The remaining 20%, with a week.

Question - I work with Spyder & and it's static code analysis that uses PyLint.  I used the autopep8 tool at the start.   Is there any other tools that I can use?  For instance, to refactor the camelcase of objects that get sprinkled through the project?

**Comment by kissgyorgy** [comment]
Your IDE or editor. PyCharm is very good in refactoring names, or you can use regex:
`re.sub('([A-Z])', lambda m:"_" + m.group(1).lower(), identifier)[1:]`

**Comment by jnmclarty** [comment]
I'm wrapping up what I'd call the planning stages for Trump, Class Names, public function_names, shouldn't need changing.  Arguments of 90% of functions shouldn't change for a while. Most files have a PEP8 score of >8.5 (depending on ignores...)  

...I'm working on the docs for the next two days, [on the docstringblowout branch of my own fork](https://github.com/jnmclarty/trump/tree/docstringblowout), but will be intermittently away from internet connectivity while I do.
