### ISSUE TITLE
Mutable default argument in a function

### ISSUE THREAD

**Issue by jnmclarty** [Equitable/trump#49]
...3 of 'em in orm.py

**Comment by eoinahern** [comment]
HI Jeff,
          ive got everything setup now. Is there any  issues you think
would be good for me to get stuck into.

Regards,
Eoin

**Comment by jnmclarty** [comment]
Hi Eoin,

I'm not sure about your skill level.  You can take a peak at any of the issues tagged ["Good First Pull Request"](https://github.com/Equitable/trump/labels/Good%20First%20Pull%20Request) ...some are as simple as a few lines.  Some are more extensive.

**Comment by jnmclarty** [comment]
I'm *not* sure about your skill level.

**Comment by jnmclarty** [comment]
Also, one super easy thing to do, to get familiar with a this project (or any project), is to compare what parts of the code are documented, and which parts aren't.  There are many functions in Trump, which haven't been added to the docs.

**Comment by eoinahern** [comment]
another way,  I have found from previous experience is to write unit tests.

**Comment by eoinahern** [comment]
I know oo python but i dont know a lot of these tools. pacakge specific to
pandas and sqlalchemy are new to me but Im working on learning those right
now so hopefully ill be able to make a decent contribution.

**Comment by jnmclarty** [comment]
@eoinahern Pandas is the root of this project, Trump wouldn't be possible without it.  SQLAlchemy, is also pretty key.  Both are amazing pieces of work.    You won't be disappointed, learning them.

**Comment by jnmclarty** [comment]
#61
